<?php

/**
 * -------------------------------------------------------------------------
 * Application Name plugin for GLPI
 * -------------------------------------------------------------------------
 *
 * Replaces the "GLPI" string that GLPI shows as its own product name.
 *
 * $CFG_GLPI['app_name'] is a plain PHP value hardcoded in
 * src/autoload/CFG_GLPI.php:47 — it has no entry in the configuration table,
 * so no administration screen can change it. Only code running before the
 * first page render can, which is what this plugin is for.
 *
 * It is read in three places:
 *   - templates/layout/parts/head.html.twig:50 — the browser tab title;
 *   - src/NotificationTemplate.php:291 — the "Automatically generated by %s"
 *     footer of every notification e-mail;
 *   - src/Glpi/Security/TOTPManager.php:135 — the issuer label MFA apps show
 *     next to the account.
 *
 * The logos are not part of this: they are files under public/pics, written
 * into the image at build time (see deploy/coolify/Dockerfile) or by
 * branding/seconv-rr/apply.sh locally.
 *
 * LICENSE
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * -------------------------------------------------------------------------
 */

use Glpi\Plugin\Hooks;

const PLUGIN_APPNAME_VERSION = '1.0.0';

/**
 * The product name this instance answers to.
 */
const PLUGIN_APPNAME_APP_NAME = 'SECONV-RR';

/**
 * Rename the application.
 *
 * Runs from the plugin boot function so the value is in place before anything
 * reads it: the kernel fires boot at priority 140, ahead of SessionStart (130)
 * and of every controller (src/Glpi/Kernel/ListenersPriority.php:64), and it
 * runs on anonymous pages too — the login page is one of them.
 */
function plugin_appname_boot(): void
{
    global $CFG_GLPI;

    $CFG_GLPI['app_name'] = PLUGIN_APPNAME_APP_NAME;
}

function plugin_init_appname(): void
{
    global $PLUGIN_HOOKS;

    $PLUGIN_HOOKS[Hooks::CSRF_COMPLIANT]['appname'] = true;
}

function plugin_version_appname(): array
{
    return [
        'name'         => 'Application Name',
        'version'      => PLUGIN_APPNAME_VERSION,
        'author'       => 'SECONV-RR',
        'license'      => 'GPLv3',
        'requirements' => [
            'glpi' => [
                'min' => '11.0',
                'max' => '12.0',
            ],
        ],
    ];
}
